import { StyleSheet } from '@react-pdf/renderer';

// All of your original styles are now in this dedicated file
export const styles = StyleSheet.create({
  page: { paddingTop: 30, paddingBottom: 30, paddingHorizontal: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#000' },
  header: { marginBottom: 15 },
  headerNameTitle: { fontSize: 16, fontWeight: 'bold', textAlign: 'center', marginBottom: 5 },
  contactInfoLine1: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', fontSize: 10, color: '#000', flexWrap: 'wrap', marginBottom: 30 },
  contactItem: { marginHorizontal: 3, textDecoration: 'none', color: '#000' },
  contactLink: { color: '#007bff', textDecoration: 'underline' },
  contactSeparator: { marginHorizontal: 3, color: '#000' },
  headerDobNationality: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', fontSize: 10, color: '#000', marginTop: 5 },
  dobGroup: { flexDirection: 'row', alignItems: 'center' },
  headerDobLabel: { marginRight: 150 },
  headerDobValue: {},
  nationalityGroup: { flexDirection: 'row', alignItems: 'center' },
  headerNationalityLabel: { marginRight: 150 },
  headerNationalityValue: {},
  section: { marginTop: 10 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', borderBottomWidth: 1.5, borderBottomColor: '#000', paddingBottom: 4, marginBottom: 8 },
  summaryText: { fontSize: 10, lineHeight: 1.4, color: '#000' },
  experienceItem: { marginBottom: 15 },
  experienceHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', fontSize: 10, marginBottom: 2 },
  experienceDate: { fontWeight: 'normal', width: '35%', marginRight: 10 },
  experienceRoleCompany: { flexGrow: 1, textAlign: 'right', width: '65%' },
  experienceRole: { fontWeight: 'bold', fontSize: 10 },
  experienceCompany: { fontStyle: 'normal', fontSize: 10, color: '#000' },
  experienceSummary: { fontSize: 10, marginTop: 5, paddingLeft: 10, fontWeight: 'bold' },
  responsibilityList: { marginTop: 5, paddingLeft: 10 },
  responsibilityItem: { fontSize: 10, marginBottom: 3, flexDirection: 'row' },
  bullet: { width: 5, marginRight: 5 },
  responsibilityText: { flex: 1 },
  subResponsibilityList: { paddingLeft: 20, marginTop: 3 },
  subResponsibilityItem: { fontSize: 10, marginBottom: 2, flexDirection: 'row' },
  numberedBullet: { width: 10, marginRight: 5 },
  educationItem: { marginBottom: 10 },
  educationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', fontSize: 10, marginBottom: 5 },
  educationPeriod: { fontWeight: 'normal' },
  educationDegree: { fontWeight: 'bold' },
  educationDetailList: { paddingLeft: 10 },
  educationDetailItem: { fontSize: 10, marginBottom: 2, flexDirection: 'row' },
  skillCategory: { marginBottom: 8 },
  skillCategoryTitle: { fontSize: 11, fontWeight: 'bold', marginBottom: 4 },
  skillList: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  skillItem: { fontSize: 10, width: '48%', marginBottom: 2 },
  languageItem: { flexDirection: 'row', fontSize: 10, marginBottom: 2, width: '48%' },
  languageName: { fontWeight: 'normal', width: '50%' },
  languageLevel: { flexGrow: 1, textAlign: 'right' },
});